language: scala
scala:
  - 2.12.6
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - bash docker_build.sh

after_script:
  - docker images

before_deploy:
  - pip install --user awscli
  - pip install ecs-deploy
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-1)

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
